docs: updated starter pack
Fixed breaking changes, synced with starter pack

Removed redundant files

Signed-off-by: annecyh <anne.chew@canonical.com>

diff --git a/docs/.readthedocs.yaml b/docs/.readthedocs.yaml
--- a/docs/.readthedocs.yaml
+++ b/docs/.readthedocs.yaml
@@ -12,7 +12,17 @@ build:
     python: "3.11"
   jobs:
     pre_install:
-      - git fetch --unshallow || true
+    - git fetch --unshallow || true
+    post_checkout:
+    # Cancel building pull requests when there aren't changed in the docs directory.
+    # If there are no changes (git diff exits with 0) we force the command to return with 183.
+    # This is a special exit code on Read the Docs that will cancel the build immediately.
+    # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
+    - |
+      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- 'docs/' '.readthedocs.yaml';
+      then
+        exit 183;
+      fi
 
 # Build documentation in the docs/ directory with Sphinx
 sphinx:
@@ -21,11 +31,10 @@ sphinx:
   fail_on_warning: true
 
 # If using Sphinx, optionally build your docs in additional formats such as PDF
-# PDF disabled because of https://github.com/canonical/real-time-ubuntu-docs/issues/84
-# formats:
-#   - pdf
+formats:
+- pdf
 
 # Optionally declare the Python requirements required to build your docs
 python:
   install:
-    - requirements: docs/.sphinx/requirements.txt
+  - requirements: docs/.sphinx/requirements.txt
